# Generated by Django 2.0.2 on 2018-03-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='owner',
            field=models.CharField(max_length=250),
        ),
    ]
